<?php
include '../PHPExcel/IOFactory.php';
include '../PHPExcel.php';
header("Content-type: text/html;charset=UTF-8");
$host       = 'localhost';
$username   = 'root';
$password   = '';
$database   = 'staff_manager';	
$con = mysql_connect($host, $username, $password);
mysql_select_db($database, $con);

mysql_query("SET CHARACTER SET utf8");
if(@$_REQUEST['user_id'])
{
	$user_id = $_REQUEST['user_id'];
	$month_confirm1 = $_REQUEST['month_confirm1'];
	$data = date("m-Y",strtotime($month_confirm1));
	$end_loop = date("t", strtotime($month_confirm1));
	$month_confirm = date("Y-m", strtotime($month_confirm1));
	$sql1 = "select * from user where id=".$user_id;
	$get_user = mysql_query($sql1);
	$row2 = mysql_fetch_array($get_user);
	$objPHPExcel = new PHPExcel();
	header('Content-type: application/vnd.ms-excel');
	header('Content-Disposition: attachment; filename="luongthang-'.$data.'-'.$row2['name'].'.xls"');
	$objPHPExcel->getProperties()->setCreator("Paditech")
					->setLastModifiedBy("Admin")
					->setTitle("Office 2007 XLSX Test Document")
					->setSubject("Office 2007 XLSX Test Document")
					->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
					->setKeywords("office 2007 openxml php")
					->setCategory("Test result file");
	$objPHPExcel->getActiveSheet()->setTitle('Thống Kê Lương');
	$styleArray = array(
		  'borders' => array(
			  'allborders' => array(
				  'style' => PHPExcel_Style_Border::BORDER_DOUBLE,
				  'color' => array(
					 'rgb' => '808080'
				 )
			  )
		  )
	  );
	
	$arrayCount1 = 1;
	$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(40);
	$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(40);
	$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(40);
	$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(40);
	$objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A'.$arrayCount1, 'Ngày')
            ->setCellValue('B'.$arrayCount1, 'Thời Gian Bắt Đầu')
			->setCellValue('C'.$arrayCount1, 'Thời Gian Kết Thúc')
			->setCellValue('D'.$arrayCount1, 'Thời Gian OT');
	$objPHPExcel->getActiveSheet()->getStyle('A'.$arrayCount1)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->getStyle('B'.$arrayCount1)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->getStyle('C'.$arrayCount1)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->getStyle('D'.$arrayCount1)->getFont()->setBold(true);
		$arrayCount1++;
	$total_time = 0;
	$time = 0;
	$time1 = 0;
	$total_ot = 0;
	$time_inmonth = 0;
	for($i = 1;$i<=$end_loop;$i++)
	{
		$startday =  date("Y-m-d", strtotime($i."-".$data));
		$dayname =  date("N", strtotime($i."-".$data));
		
		if($dayname == 1)
		{
			$thu = "Thứ Hai";
		}
		if($dayname == 2)
		{
			$thu = "Thứ Ba";
		}
		if($dayname == 3)
		{
			$thu = "Thứ Tư";
		}
		if($dayname == 4)
		{
			$thu = "Thứ Năm";
		}
		if($dayname == 5)
		{
			$thu = "Thứ Sáu";
		}
		if($dayname == 6)
		{
			$thu = "Thứ Bảy";
		}
		if($dayname == 7)
		{
			$thu = "Chủ Nhật";
		}
		$results = mysql_query("select * from staff_time where user_id='".$user_id."' and time_start like '%".$startday."%'");
		//$get_cal = mysql_query($sql);
		$num_rows = @mysql_num_rows($results);	
		if($dayname != 6 && $dayname != 7)
		{
			$time_inmonth += 8;
		}
		if($num_rows > 0)
		{
			$row = mysql_fetch_array($results);	
			$total_time += strtotime($row['time_end']) - strtotime($row['time_start']) - 3600;
			$time =  date("H",strtotime($row['time_OT'])) * 3600;
			$time1 =  date("i",strtotime($row['time_OT'])) * 60;
			$total_ot += $time + $time1;
			if($row['is_day_leave'] == 1)
			{
				$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A'.$arrayCount1, $thu." , ".$i."-".$data);
				$objPHPExcel->getActiveSheet()->getStyle('A'.$arrayCount1.':D'.$arrayCount1)->applyFromArray($styleArray);
				$objPHPExcel->getActiveSheet()
					->getStyle('A'.$arrayCount1.':D'.$arrayCount1)
					->getFill()
					->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
					->getStartColor()
					->setARGB('F28A8C');
				$arrayCount1++;
			}
			else
			{
				$objPHPExcel->getActiveSheet()->getStyle('A'.$arrayCount1.':D'.$arrayCount1)->applyFromArray($styleArray);
				$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A'.$arrayCount1, $thu." , ".$i."-".$data)
					->setCellValue('B'.$arrayCount1, date("H:i",strtotime($row['time_start'])))
					->setCellValue('C'.$arrayCount1, date("H:i",strtotime($row['time_end'])))
					->setCellValue('D'.$arrayCount1, date("H:i",strtotime($row['time_OT'])));
				$arrayCount1++;
				
			}
			
		}
		else
		{
			$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A'.$arrayCount1, $thu." , ".$i."-".$data);
			$objPHPExcel->getActiveSheet()->getStyle('A'.$arrayCount1.':D'.$arrayCount1)->applyFromArray($styleArray);
			$objPHPExcel->getActiveSheet()
					->getStyle('A'.$arrayCount1.':D'.$arrayCount1)
					->getFill()
					->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
					->getStartColor()
					->setARGB('FFDEDE');
				$arrayCount1++;
			
		}
	}
	
	$total_time = $total_time/60;
	$total_ot = $total_ot/60;
	$luongtb = $row2['luong']/$time_inmonth;
	$luongot = ($luongtb*1.5)*floor($total_ot/60)+($luongtb*1.5/60)*floor($total_ot%60);
	$luong = $luongtb*floor($total_time/60) + ($luongtb/60)*($total_time%60);
	
	$objPHPExcel->setActiveSheetIndex(0)
					->setCellValue('A'.$arrayCount1, "Tổng Thời Gian Làm : ".sprintf("%02dh %02dm", floor($total_time/60), $total_time%60).'/'.$time_inmonth)
					->setCellValue('B'.$arrayCount1, "Tổng Thời Gian OT : ".sprintf("%02dh %02dm", floor($total_ot/60), $total_ot%60))
					->setCellValue('C'.$arrayCount1, "Lương Nhận Được : ".substr(number_format(ceil($luong+$luongot),2),0,-3));
	$objPHPExcel->getActiveSheet()->getStyle('A'.$arrayCount1)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->getStyle('B'.$arrayCount1)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->getStyle('C'.$arrayCount1)->getFont()->setBold(true);
	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
	
	//$objWriter->save('../log/.xlsx');
	$objWriter->save("php://output");
}

